
// Generated by AI (GitHub Copilot)
// Author: Nisarg Raval
package com.demo.app.repository;

import com.demo.app.model.AccountAlias;
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.Optional;

public interface AccountAliasRepository extends JpaRepository<AccountAlias, Long> {
    Optional<AccountAlias> findByAlias(String alias);
}
