
// Generated by AI (GitHub Copilot)
// Author: Nisarg Raval
package com.demo.app.repository;

import com.demo.app.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.Optional;

public interface UserRepository extends JpaRepository<User, Long> {
    Optional<User> findByEmail(String email);
}
