
// Generated by AI (GitHub Copilot)
// Author: Nisarg Raval
package com.demo.app.service;

import com.demo.app.model.AccountAlias;
import com.demo.app.repository.AccountAliasRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import java.util.Optional;
import java.util.List;

@Service
public class AccountAliasService {
    @Autowired
    private AccountAliasRepository accountAliasRepository;

    public AccountAlias createAlias(AccountAlias alias) {
        return accountAliasRepository.save(alias);
    }

    public Optional<AccountAlias> findByAlias(String alias) {
        return accountAliasRepository.findByAlias(alias);
    }

    public Optional<AccountAlias> findById(Long id) {
        return accountAliasRepository.findById(id);
    }

    public List<AccountAlias> findAll() {
        return accountAliasRepository.findAll();
    }

    public void deleteById(Long id) {
        accountAliasRepository.deleteById(id);
    }

    public AccountAlias updateAlias(AccountAlias alias) {
        return accountAliasRepository.save(alias);
    }
}
