openapi: 3.0.3
info:
  title: Account Alias Demo API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /auth/register:
    post:
      summary: User Registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered
        '409':
          description: User already registered
  /auth/login:
    post:
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
  /user/me:
    get:
      summary: Get My Profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
    put:
      summary: Update My Profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: Updated
  /alias:
    post:
      summary: Create Account Alias
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AliasRequest'
      responses:
        '201':
          description: Created
        '409':
          description: Alias already exists
    get:
      summary: List My Aliases
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of aliases
  /alias/{aliasId}:
    get:
      summary: Get Alias Details
      security:
        - bearerAuth: []
      parameters:
        - name: aliasId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Alias details
    put:
      summary: Update Alias Status
      security:
        - bearerAuth: []
      parameters:
        - name: aliasId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAliasRequest'
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete Alias
      security:
        - bearerAuth: []
      parameters:
        - name: aliasId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    UpdateUserRequest:
      type: object
      properties:
        name:
          type: string
    AliasRequest:
      type: object
      properties:
        name:
          type: string
    UpdateAliasRequest:
      type: object
      properties:
        status:
          type: string
